spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lfs?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 666666
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  # JPA相关配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    # formatSQL
    properties:
      hibernate:
        format_sql: true

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: springboot-lfs
  # JWT的超时时间 (60*60*24*7)
  expiration: 604800
  # JWT负载头
  tokenHead: 'Bearer '

whitelist:
  urls: #配置白名单路径
    - "/doc.html"
    - "/swagger-resources/**"
    - "/swagger/**"
    - "/**/v2/api-docs"
    - "/**/*.js"
    - "/**/*.css"
    - "/**/*.png"
    - "/**/*.ico"
    - "/webjars/springfox-swagger-ui/**"
    - "/actuator/**"
    - "/druid/**"
    - "/user/login"
    - "/user/logout"