spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lfs?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: postgres
    password: 666666
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 20
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 5000
      # 检测连接是否有效
      connection-test-query: select 1
  # JPA相关配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    # formatSQL
    properties:
      hibernate:
        format_sql: true
  # 缓存
  cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=500,initialCapacity=100,expireAfterAccess=600s

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: pisces-lfs
  # JWT的超时时间 (60*60*24*7)
  expiration: 604800
  # JWT负载头
  tokenHead: 'Bearer '

# OpenApi 配置
springdoc:
  swagger-ui:
    # 文档访问路径
    path: "/swagger-ui.html"
  packages-to-scan: com.besscroft.lfs
  api-docs:
    # 是否开启
    enabled: true

whitelist:
  urls: #配置白名单路径
    - "/*/*.js"
    - "/*/*.css"
    - "/*/*.png"
    - "/*/*.ico"
    - "/swagger-ui.html"
    - "/swagger-ui/index.html"
    - "/v3/*"
    - "/actuator/*"
    - "/user/login"
    - "/user/logout"
    - "/actuator/*"

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        # 监控项配置
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      # 开启显示全部细节
      show-details: always
    shutdown:
      # 启用接口关闭 SpringBoot
      enabled: false

# 日志文件地址（提供给程序读取的地址，输出地址请在 logback-spring.xml 配置）
logging:
  file:
    name: logs/${spring.application.name}/info.log
